title = "CareerBoost"
baseURL = "https://xenodochial-lovelace-e17126.netlify.app"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/CareerBuilder"
  instagram = "https://www.instagram.com/ENTREPRENEUR/"
  youtube = "https://www.youtube.com/watch?v=we7zHcsgo0o"
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jenny-guo/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-red"
  featured_image = "https://images.unsplash.com/photo-1551892589-865f69869476?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&dl=guille-alvarez-IcI3FizU9Cw-unsplash.jpg"
  recent_posts_number = 2

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


